### ISSUE TITLE
The exclude rules support files?

### ISSUE THREAD

**Issue by yeqown** [GaijinEntertainment/go-exhaustruct#67]
I tried as following rules, in golangci-lint:
```yaml
linters-settings:
  exhaustruct:
    include:
      - "^.*Factory$"
      - "^.*Base$"
    exclude:
      - "^.*_test.go$"
```

but it doesn't work, so I wonder if it supports or not.

**Comment by xobotyi** [comment]
Golangci-lint still uses v2

**Comment by xobotyi** [comment]
Closing as golangcilint now updated to v3

**Comment by pantafive** [comment]
```yaml
issues:
  exclude-rules:
  - path: ^.*_test\.go$
    linters:
    - exhaustruct
```

works for me in golangci-lint
